# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9328c117c23b45d4ab526c0a0e08701eaad8fa06e994939ea0258edadbb34652fb6cdbd0efe9327cbff51f90ef7fd0cbd2774b851be9443415508b0450660c09

test:
  secret_key_base: 231125f15379b37263cce03191932aa394dace9889bdfa0719e012b37b4db3e61f142875cf20aa3e1eb838032fc29dfe6a41c2e2edcf23683f610069e9f3b8bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
